### ISSUE TITLE
Article CSS Changes

### ISSUE THREAD

**Issue by JBird608** [JBird608/JoeCurran_Codes#6]
Layout Changes

```css
p {
   font-size: 1rem;
   margin: 1rem 0 0.5rem;
   // Top Edited, Bottom Added
}

h1, h2, h3, h4, h5, h6 {
   margin: 2rem 0 0.5rem 0;
   //Top Edited
}

#core_content .article_head h1 {
   margin-top: 0;
}
```
